---
- hosts: "localhost"
  vars:
    wsl_user: xiabai84
  connection: "local"
  become: true
  become_method: sudo
  tasks:
    - import_role:
        name: sysconfig
    - import_role:
        name: pylibs
    - import_role:
        name: jdk
    - import_role:
        name: docker
