- name: Install tmux
  apt: pkg=tmux state=present

- name: Copy tmux conf
  become: true
  become_user: root
  copy:
    src: .tmux.conf
    dest: ~/
    owner: '{{ wsl_user }}'
    group: '{{ wsl_user }}'
    mode: 0775
    backup: yes